table 'Dynamic Logo'
	lineageTag: b4dc28af-103e-488c-897e-ae088189a3b2

	measure DynLogoHtml = "<div style='text-align:center'><img src='"&FIRSTNONBLANK('Dynamic Logo'[Logo],'Dynamic Logo'[Logo])&"' style='height:100vh'></div>"
		lineageTag: 8d00950f-e403-49df-8481-0c763feb16cb

	column id
		dataType: string
		lineageTag: 1abfbe41-0928-495e-b5d4-9bbf33d18fcf
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column Logo
		dataType: string
		lineageTag: 6012dafc-db2b-473d-b3b8-fa23a5c0d75b
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Logo

		annotation SummarizationSetBy = Automatic

	partition 'Dynamic Logo' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("PHvXlqvMkua7nFv6NN71XOGE8Eb4s+YChPcIK55+UvXPTO1VRlsIkxHxmczI//zn", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [id = _t, Logo = _t]),
				    #"Type modifi" = Table.TransformColumnTypes(Source,{{"id", type text}, {"Logo", type text}})
				in
				    #"Type modifi"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

