table GLA
	lineageTag: 759f2031-e42c-4aae-b714-7ea54f6eb10c

	column ID_Ste
		dataType: string
		lineageTag: efe95293-58f2-4fa5-8e62-0bfeddaba008
		summarizeBy: none
		sourceColumn: ID_Ste

		annotation SummarizationSetBy = Automatic

	column id_ledger_entries
		dataType: string
		lineageTag: 0913fb70-1c80-442f-af87-7d8b3aa35ed8
		summarizeBy: none
		sourceColumn: id_ledger_entries

		annotation SummarizationSetBy = Automatic

	column piece_number
		dataType: string
		lineageTag: 8bb8dda2-8ff2-4d6e-978a-01aadd02c006
		summarizeBy: none
		sourceColumn: piece_number

		annotation SummarizationSetBy = Automatic

	column Invoice_number
		dataType: string
		lineageTag: ab190ca0-134c-443c-b371-60676926f32e
		summarizeBy: none
		sourceColumn: Invoice_number

		annotation SummarizationSetBy = Automatic

	column Thirdparty_identifier
		dataType: string
		lineageTag: 426cc61d-bfe3-4445-af37-c3369dfa85c5
		summarizeBy: none
		sourceColumn: Thirdparty_identifier

		annotation SummarizationSetBy = Automatic

	column Thirdparty
		dataType: string
		lineageTag: 7689305a-d95e-450d-a399-121fa59c5487
		summarizeBy: none
		sourceColumn: Thirdparty

		annotation SummarizationSetBy = Automatic

	column SIREN
		dataType: string
		lineageTag: aec67345-18a8-453a-9327-610f59a3dc41
		summarizeBy: none
		sourceColumn: SIREN

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: c0609411-83a2-40e2-8c70-676fd7450851
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Journal_code
		dataType: string
		lineageTag: 9deb538a-44f0-492a-8afd-483903f852de
		summarizeBy: none
		sourceColumn: Journal_code

		annotation SummarizationSetBy = Automatic

	column Analytical_axis
		dataType: string
		lineageTag: cc8eee8a-19a4-4821-a5e4-ca0137b4dc55
		summarizeBy: none
		sourceColumn: Analytical_axis

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: ff146b3f-b186-4306-8441-17e74b271880
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: 1dfc9bcd-6c87-4707-be8b-8394165a475c
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Exchange_rate
		dataType: double
		lineageTag: 3a4e5a7f-f27e-44f3-968f-116a4ec2fdb0
		summarizeBy: sum
		sourceColumn: Exchange_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Debit_Currency
		dataType: double
		lineageTag: 5a2c7fc5-d0f8-49ff-ab91-4b4a0d14c6db
		summarizeBy: sum
		sourceColumn: Debit_Currency

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Credit_Currency
		dataType: double
		lineageTag: bdb0d1cb-9175-4163-8ecd-ca71d9042ee9
		summarizeBy: sum
		sourceColumn: Credit_Currency

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Balance_Currency
		dataType: double
		lineageTag: 17ce09dd-a731-4f25-a3eb-4d336fcfc297
		summarizeBy: sum
		sourceColumn: Balance_Currency

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Debit
		dataType: double
		lineageTag: c5868d8f-e807-4cff-91c1-679415886aeb
		summarizeBy: sum
		sourceColumn: Debit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Credit
		dataType: double
		lineageTag: 21b59a6a-318d-48db-be3c-1de03fd82afe
		summarizeBy: sum
		sourceColumn: Credit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Balance
		dataType: double
		lineageTag: 1946636c-d75b-4736-8fb6-92bd359ef681
		summarizeBy: sum
		sourceColumn: Balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Line_identifier
		dataType: string
		lineageTag: 7b42d71d-b255-4f7b-82d4-4b0086ddd882
		summarizeBy: none
		sourceColumn: Line_identifier

		annotation SummarizationSetBy = Automatic

	column Plan_item_number
		dataType: string
		lineageTag: eb6694f5-c488-4bf6-afe0-98c2b5e76548
		summarizeBy: none
		sourceColumn: Plan_item_number

		annotation SummarizationSetBy = Automatic

	column Plan_item_label
		dataType: string
		lineageTag: ae2595f3-17be-4d97-bed5-121c22ac79a4
		summarizeBy: none
		sourceColumn: Plan_item_label

		annotation SummarizationSetBy = Automatic

	column VAT_rate
		dataType: string
		lineageTag: 8b410a72-5493-49fa-a25c-1c56fd026c64
		summarizeBy: none
		sourceColumn: VAT_rate

		annotation SummarizationSetBy = Automatic

	column Plan_item_Country
		dataType: string
		lineageTag: eb2f5dc6-d92e-49c4-a84f-2606a3a548a0
		summarizeBy: none
		sourceColumn: Plan_item_Country

		annotation SummarizationSetBy = Automatic

	column Entry_piece
		dataType: string
		lineageTag: 6bc59dd0-0224-471c-8ca0-9d225cb06280
		summarizeBy: none
		sourceColumn: Entry_piece

		annotation SummarizationSetBy = Automatic

	column Line_label
		dataType: string
		lineageTag: c529e326-5cee-46e5-8e05-6625370f2d9e
		summarizeBy: none
		sourceColumn: Line_label

		annotation SummarizationSetBy = Automatic

	partition GLA = m
		mode: import
		queryGroup: 'model tables'
		source =
				let
				    Source = Sql.Databases("mhirzqqnk57e7anmxqvc3cldyq-ad6po2r4ekrefdnhlqka77jyjq.datawarehouse.fabric.microsoft.com"),
				    GLA = Source{[Name="fact_1_GLA"]}[Data],
				    Query = "
				        SELECT *
				        FROM dbo.fact_1_gla_actual_inline
				        WHERE ID_Ste IN (21912624)
				    ",
				    NativeQuery = Value.NativeQuery(GLA, Query),
				    #"Type modifié" = Table.TransformColumnTypes(NativeQuery,{{"Date", type date}, {"Line_identifier", type text}, {"Thirdparty_identifier", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Type modifié",{"Deadline"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

